import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "airbnb2",
  description: "Generated by create next app",
};

// import { Router } from "next/router";
// import ProgressBar from "@badrap/bar-of-progress";

// const progress = new ProgressBar({
//   size: 4,
//   color: "#FE595E",
//   className: "z-50",
//   delay: 100,
// });

// Router.events.on("routeChangeStart", progress.start);
// Router.events.on("routeChangeComplete", progress.finish);
// Router.events.on("routeChangeError", progress.finish);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
